INSERT INTO `becario`.`escuela` (`nombre_escuela`, `created_at`) VALUES ('Escuela de arquitectura, Arte y Diseño', '2019-05-08 00:00:00');
INSERT INTO `becario`.`escuela` (`nombre_escuela`, `created_at`) VALUES ('Escuela de Ingenieria y Tecnologias de Informacion', '2019-05-08 00:00:00');
INSERT INTO `becario`.`escuela` (`nombre_escuela`, `created_at`) VALUES ('Escuela de Negocios, Ciencias Sociales y Humanidades', '2019-05-08 00:00:00');
INSERT INTO `becario`.`escuela` (`nombre_escuela`, `created_at`) VALUES ('Escuela de Biotecnología y Alimentos', '2019-05-08 00:00:00');
INSERT INTO `becario`.`escuela` (`nombre_escuela`, `created_at`) VALUES ('Escuela de Medicina y Ciencias de la Salud', '2019-05-08 00:00:00');

INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Arquitectura', '1', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Diseño Industrial', '1', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Departamento de Arte', '1', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Ingenieria Civil', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Sistemas de Información', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Mecánica', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Quimica', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Ing. Eléctrica y Computación', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Cs. Computacionales', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Mecatrónica y Automatización', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Física', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Matemáticas', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Gestión Empresarial y Talento Humano', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Mercadotecnia y Negocios Internacionales', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Contabilidad y Finanzas', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Lenguas Modernas', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Estudios Humanísticos', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Relaciones Internacionales', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Comunicación y Periodísmo', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Filosofía y Ética', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Economía', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Derecho', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Administrativo', '4', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Desarrollo Académico', '4', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Coordinación y Enlace', '4', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Ciencias Básicas', '5', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Nutrición', '5', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Ética y Profesionalismo', '5', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Ciencias Médicas Básicas', '5', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Ciencias Clínicas', '5', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Depto. de Enfermería', '5', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Dir. Área de Posgrado Esc. Med.', '5', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Departamento Atención a alumnos', '5', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Depto. de Odontología', '5', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Ingeniería Biomédica', '5', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Admón. de Sistemas de Salud', '5', '2019-05-08 00:00:00');
INSERT INTO `becario`.`departamento` (`nombre_departamento`, `id_escuela`, `created_at`) VALUES ('Dir. Area de Pregrado Esc. Med.', '5', '2019-05-08 00:00:00');

INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('ARQ', 'Arquitectura', '1', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LDI', 'Lic. en Diseño Industrial', '1', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LAD', 'Lic. en Animación y Arte Digitañ', '1', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('IC', 'Ingenieria Civil', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('IIS', 'Ingeniero Industrial y de Sistemas', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('IMA/IME', 'Ing- Mecánico Administrador/Electricista', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('IQA/IQS', 'Ing. Químico Administrador/Sistemas', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('IDS', 'Ing. en Desarrollo Sustentable', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('ITC/ISC', 'Ing. en Tecnologías Computacionales', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('IFI', 'Ing. Físico Industrial', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('ITE', 'Ing. en Tecnologías Electrónicas', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('ISD', 'Ing. en Sitemas Digitales y Robótica', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('ITIC', 'Ing. en Tecnologías de Información y Comunicaciones', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('ITM', 'Ing. en Telecomunicaciones y Microelectrónica', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LATI', 'Lic. en Administración de Tecnologías de Información', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('INT', 'Ing. en Negocios y Tecnologias', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('IMT', 'Ing en Mecatrónica', '2', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LPO', 'Lic. en Psicología Organizacional', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LCP', 'Lic. en Contaduría Pública y Finanzas', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LIN', 'Lic. en Negocios Internacionales', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LEM', 'Lic. en Mercadotecnia', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LAF', 'Lic. en Administración Financiera', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LAE', 'Lic. en Administración de Empresas', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LCDE', 'Lic. en Creación y Desarrollo de Empresas', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LRI', 'Lic. en Relaciones Internacionales', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LPL', 'Lic. en Ciencia Política', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LLE', 'Lic. en Lengua y Literatura Hispánicas', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LCC', 'Lic. en Ciencias de la Comunicación', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LMI', 'Lic. en Medios de Información', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('IMI', 'Ing. en Producción Musical', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LEC', 'Lic. en Economía', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LED', 'Lic. en Derecho', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LDF', 'Lic. en Derecho y Finanzas', '3', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('IBT', 'Ing. en Biotecnologías', '4', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('IAB/IA', 'Ing. en Agrobiotecnología', '4', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('IIA', 'Ing. en Industrias Alimentarias', '4', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LCQ', 'Lic. en Ciencias Químicas', '4', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('IBN/LAN', 'Lic. en Agronegocios', '4', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('MC', 'Médico Cirujano', '5', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('MO', 'Médico Cirujano Odontólogo', '5', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('IMD', 'Ing. Biomédico', '5', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LNB', 'Lic. en Nutrición y Bienest. Int.', '5', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LAS', 'Lic. en Admón y Sistemas de Salud', '5', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LCE', 'Lic. en Cienc. de la Enfermería', '5', '2019-05-08 00:00:00');
INSERT INTO `becario`.`carrera` (`siglas_carrera`, `carrera_nombre`, `id_escuela`, `created_at`) VALUES ('LBC', 'Lic. en Biociencias', '5', '2019-05-08 00:00:00');

INSERT INTO `becario`.`estudiante` (`matricula`, `nombre_completo`, `celular`, `semestre_actual`, `id_carrera`, `asignable_sn`, `estatus_assignable_sn`, `tipo_beca`, `contrasena`, `email`) VALUES ('A01281459', 'Federico Alcerreca', '8181818180', '6', '10', '1', '1', '2', 'contraseña', 'email@email.com');
INSERT INTO `becario`.`estudiante` (`matricula`, `nombre_completo`, `celular`, `semestre_actual`, `id_carrera`, `asignable_sn`, `estatus_assignable_sn`, `tipo_beca`, `contrasena`, `email`) VALUES ('A01281234', 'Salvador Pousa', '8134567895', '3', '1', '1', '1', '1', 'algo', 'algo@mail.com');
INSERT INTO `becario`.`estudiante` (`matricula`, `nombre_completo`, `celular`, `semestre_actual`, `id_carrera`, `asignable_sn`, `estatus_assignable_sn`, `tipo_beca`, `contrasena`, `email`) VALUES ('A01282345', 'Angel Arnal', '8146379284', '5', '20', '1', '1', '2', 'clever', 'clever@mail.com');
INSERT INTO `becario`.`estudiante` (`matricula`, `nombre_completo`, `celular`, `semestre_actual`, `id_carrera`, `asignable_sn`, `estatus_assignable_sn`, `tipo_beca`, `contrasena`, `email`) VALUES ('A01283456', 'Pablo Indiano', '8123547965', '4', '21', '1', '1', '1', 'nose', 'nose@mail.com');
INSERT INTO `becario`.`estudiante` (`matricula`, `nombre_completo`, `celular`, `semestre_actual`, `id_carrera`, `asignable_sn`, `estatus_assignable_sn`, `tipo_beca`, `contrasena`, `email`) VALUES ('A01284567', 'Jonatán Espina', '8163924570', '6', '15', '1', '1', '1', 'escribe', 'escribe@mail.com');
INSERT INTO `becario`.`estudiante` (`matricula`, `nombre_completo`, `celular`, `semestre_actual`, `id_carrera`, `asignable_sn`, `estatus_assignable_sn`, `tipo_beca`, `contrasena`, `email`) VALUES ('A01285678', 'Valentino Villacrés', '8107359076', '7', '18', '1', '1', '3', 'putin', 'atricula@email.com');
INSERT INTO `becario`.`estudiante` (`matricula`, `nombre_completo`, `celular`, `semestre_actual`, `id_carrera`, `asignable_sn`, `estatus_assignable_sn`, `tipo_beca`, `contrasena`, `email`) VALUES ('A01286789', 'Ismael Tejedor', '8164823079', '2', '25', '1', '0', '2', 'obama', 'A01286789@email.com');
INSERT INTO `becario`.`estudiante` (`matricula`, `nombre_completo`, `celular`, `semestre_actual`, `id_carrera`, `asignable_sn`, `estatus_assignable_sn`, `tipo_beca`, `contrasena`, `email`) VALUES ('A01281472', 'Guillermo Mariano', '8146793581', '1', '7', '1', '0', '1', 'ah', 'a@hotmail.com');
INSERT INTO `becario`.`estudiante` (`matricula`, `nombre_completo`, `celular`, `semestre_actual`, `id_carrera`, `asignable_sn`, `estatus_assignable_sn`, `tipo_beca`, `contrasena`, `email`) VALUES ('A01284725', 'Jose Juderias', '8143687524', '3', '9', '1', '1', '1', 'ya', 'b@hotmail.com');
INSERT INTO `becario`.`estudiante` (`matricula`, `nombre_completo`, `celular`, `semestre_actual`, `id_carrera`, `asignable_sn`, `estatus_assignable_sn`, `tipo_beca`, `contrasena`, `email`) VALUES ('A01287258', 'Manuel Seco', '8104350975', '2', '19', '0', '0', '2', 'matame', 'c@hotmail.com');
INSERT INTO `becario`.`estudiante` (`matricula`, `nombre_completo`, `celular`, `semestre_actual`, `id_carrera`, `asignable_sn`, `estatus_assignable_sn`, `tipo_beca`, `contrasena`, `email`) VALUES ('A01282558', 'Bruno Mancebo', '8103406508', '5', '22', '0', '0', '2', 'plox', 'd@hotmail.com');
INSERT INTO `becario`.`estudiante` (`matricula`, `nombre_completo`, `celular`, `semestre_actual`, `id_carrera`, `asignable_sn`, `estatus_assignable_sn`, `tipo_beca`, `contrasena`, `email`) VALUES ('A01285836', 'Gustavo Alcabú', '8190765740', '6', '17', '1', '1', '3', 'ya', 'e@hotmail.com');
INSERT INTO `becario`.`estudiante` (`matricula`, `nombre_completo`, `celular`, `semestre_actual`, `id_carrera`, `asignable_sn`, `estatus_assignable_sn`, `tipo_beca`, `contrasena`, `email`) VALUES ('A01288369', 'Raúl Valerio', '8190763280', '7', '5', '1', '1', '3', 'no', 'f@hotmail.com');
INSERT INTO `becario`.`estudiante` (`matricula`, `nombre_completo`, `celular`, `semestre_actual`, `id_carrera`, `asignable_sn`, `estatus_assignable_sn`, `tipo_beca`, `contrasena`, `email`) VALUES ('A01146795', 'Emiliano Gonzales', '8143506280', '8', '4', '0', '0', '1', 'quiero', 'g@hotmail.com');
INSERT INTO `becario`.`estudiante` (`matricula`, `nombre_completo`, `celular`, `semestre_actual`, `id_carrera`, `asignable_sn`, `estatus_assignable_sn`, `tipo_beca`, `contrasena`, `email`) VALUES ('A01179846', 'Cristian Tenorio', '81709507', '9', '13', '0', '1', '1', 'hacer', 'h@hotmail.com');
INSERT INTO `becario`.`estudiante` (`matricula`, `nombre_completo`, `celular`, `semestre_actual`, `id_carrera`, `asignable_sn`, `estatus_assignable_sn`, `tipo_beca`, `contrasena`, `email`) VALUES ('A01146779', 'Guillermo Ordóñez', '8164973250', '6', '2', '0', '1', '2', 'esto', 'i@hotmail.com');

INSERT INTO `becario`.`colaboradores` (`nomina`, `nombre_completo`, `profesor_sn`, `tipo_contrato`, `id_departamento`, `oficina`, `celular`, `contrasena`, `email`, `created_at`) VALUES ('L07694538', 'Dylan Martí', '1', '1', '1', 'aqui', '814639576', 'aquino', 'z@hotmail.com', '2019-05-08 00:00:00');
INSERT INTO `becario`.`colaboradores` (`nomina`, `nombre_completo`, `profesor_sn`, `tipo_contrato`, `id_departamento`, `oficina`, `celular`, `contrasena`, `email`, `created_at`) VALUES ('L07298463', 'Israel Alcabú', '1', '1', '2', 'alla', '8123467895', 'allano', 'x@hotmail.com', '2019-05-08 00:00:00');
INSERT INTO `becario`.`colaboradores` (`nomina`, `nombre_completo`, `profesor_sn`, `tipo_contrato`, `id_departamento`, `oficina`, `celular`, `contrasena`, `email`, `created_at`) VALUES ('L07294865', 'Leticia Ordóñez', '1', '2', '3', 'acuya', '8164973256', 'acuyano', 'y@hotmail.com', '2019-05-08 00:00:00');
INSERT INTO `becario`.`colaboradores` (`nomina`, `nombre_completo`, `profesor_sn`, `tipo_contrato`, `id_departamento`, `oficina`, `celular`, `contrasena`, `email`, `created_at`) VALUES ('L067819435', 'Joaquín Veltran', '0', '2', '4', 'ceci', '8183640927', 'cecinon', 'w@hotmail.com', '2019-05-08 00:00:00');
INSERT INTO `becario`.`colaboradores` (`nomina`, `nombre_completo`, `profesor_sn`, `tipo_contrato`, `id_departamento`, `oficina`, `celular`, `contrasena`, `email`, `created_at`) VALUES ('L03164852', 'Paquita del Barrio', '0', '3', '5', 'cela', '8160709082', 'celanon', 't@hotmail.com', '2019-05-08 00:00:00');

INSERT INTO `becario`.`solicitud_becaria` (`aprovada`, `id_colaborador`, `id_estudiante`, `fecha`, `periodo`, `fecha_asignacion`, `fecha_aceptacion`, `evaluacion`, `created_at`) VALUES ('1', '1', '1', '2019-01-01', '1', '2019-01-01', '2019-01-01', '1', '2019-05-08 00:00:00');
INSERT INTO `becario`.`solicitud_becaria` (`aprovada`, `id_colaborador`, `id_estudiante`, `fecha`, `periodo`, `fecha_asignacion`, `fecha_aceptacion`, `evaluacion`, `created_at`) VALUES ('1', '2', '2', '2019-01-02', '2', '2019-01-01', '2019-01-01', '0', '2019-05-08 00:00:00');
INSERT INTO `becario`.`solicitud_becaria` (`aprovada`, `id_colaborador`, `id_estudiante`, `fecha`, `periodo`, `fecha_asignacion`, `fecha_aceptacion`, `evaluacion`, `created_at`) VALUES ('1', '3', '3', '2019-01-03', '3', '2019-01-01', '2019-01-01', '1', '2019-05-08 00:00:00');
INSERT INTO `becario`.`solicitud_becaria` (`aprovada`, `id_colaborador`, `id_estudiante`, `fecha`, `periodo`, `fecha_asignacion`, `fecha_aceptacion`, `evaluacion`, `created_at`) VALUES ('1', '4', '4', '2019-01-04', '4', '2019-01-01', '2019-01-01', '0', '2019-05-08 00:00:00');
INSERT INTO `becario`.`solicitud_becaria` (`aprovada`, `id_colaborador`, `id_estudiante`, `fecha`, `periodo`, `fecha_asignacion`, `fecha_aceptacion`, `evaluacion`, `created_at`) VALUES ('1', '5', '5', '2019-01-05', '1', '2019-01-01', '2019-01-01', '1', '2019-05-08 00:00:00');
INSERT INTO `becario`.`solicitud_becaria` (`aprovada`, `id_colaborador`, `id_estudiante`, `fecha`, `periodo`, `fecha_asignacion`, `fecha_aceptacion`, `evaluacion`, `created_at`) VALUES ('0', '1', '6', '2019-01-06', '2', '2019-01-01', '2019-01-01', '0', '2019-05-08 00:00:00');
INSERT INTO `becario`.`solicitud_becaria` (`aprovada`, `id_colaborador`, `id_estudiante`, `fecha`, `periodo`, `fecha_asignacion`, `fecha_aceptacion`, `evaluacion`, `created_at`) VALUES ('0', '2', '7', '2019-01-07', '3', '2019-01-01', '2019-01-01', '1', '2019-05-08 00:00:00');
INSERT INTO `becario`.`solicitud_becaria` (`aprovada`, `id_colaborador`, `id_estudiante`, `fecha`, `periodo`, `fecha_asignacion`, `fecha_aceptacion`, `evaluacion`, `created_at`) VALUES ('0', '3', '8', '2019-01-08', '4', '2019-01-01', '2019-01-01', '0', '2019-05-08 00:00:00');
INSERT INTO `becario`.`solicitud_becaria` (`aprovada`, `id_colaborador`, `id_estudiante`, `fecha`, `periodo`, `fecha_asignacion`, `fecha_aceptacion`, `evaluacion`, `created_at`) VALUES ('0', '4', '9', '2019-01-08', '1', '2019-01-01', '2019-01-01', '1', '2019-05-08 00:00:00');
INSERT INTO `becario`.`solicitud_becaria` (`aprovada`, `id_colaborador`, `id_estudiante`, `fecha`, `periodo`, `fecha_asignacion`, `fecha_aceptacion`, `evaluacion`, `created_at`) VALUES ('0', '5', '10', '2019-01-10', '2', '2019-01-01', '2019-01-01', '0', '2019-05-08 00:00:00');

